core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "core"

urlpatterns = [   
    path("", views.HomeView.as_view(), name="home"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("product/<int:pk>", views.s_product, name="product"),
    path("blog/", views.BlogView.as_view(), name="blog"),
    path("post/<int:pk>", views.s_blog, name="post"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact_view, name="contact"),
    path("cart/", views.CartView.as_view(), name="cart"),
]

 
# Adicione estas linhas para servir arquivos de mídia durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

setup/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('core.urls')),
    path("user/", include('userauths.urls')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path
from . import views

app_name = "userauths"

urlpatterns = [
    path("signup/", views.register_view, name="signup"),
    path("signin/", views.login_view, name="signin"),
    path("signout/", views.logout_view, name="signout"),
]

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}Silver King{% endblock page_title %}

{% block opc_navbar %}
  <li><a href="{% url "core:home" %}">Home</a></li>
  <li><a href="{% url "core:shop" %}">Shop</a></li>
  <li><a class="active" href="{% url "core:blog" %}">Blog</a></li>
  <li><a href="{% url "core:about" %}">About</a></li>
  <li><a href="{% url "core:contact" %}">Contact</a></li>
  <li id="lg-bag"><span>{{ request.quantidade_itens_carrinho }}</span><a href="{% url "core:cart" %}"><i class="fa-solid fa-basket-shopping"></i></a></li>
  <li id="lg-user"><a href="{% url "userauths:signin" %}"><i class="fa-solid fa-user"></i></a></li>
  <a href="#" id="close"><i class="fa-solid fa-xmark"></i></a>
{% endblock opc_navbar %}

{% block content %}

  <section id="page-header" class="blog-header">
    <h2>#Readmore</h2>
    <p>Read all case studies about out products!</p>
  </section>

  <section id="blog">
    {% for post in blog_list %}
      <div class="blog-box">
          <div class="blog-img">
              <img src="{{ post.image.url }}" alt="">
          </div>
          <div class="blog-details">
              <h4>{{ post.title }}</h4>
              <p>{{ post.summary | safe }}</p>
              <a href="{% url "core:post" pk=post.pk %}">CONTINUE LENDO</a>
          </div>
          <h1>{{ post.date }}</h1>
      </div>
    {% endfor %}
  </section>

  <section id="pagination" class="section-p1">
    {% if page_obj.has_previous %}
      <a href="?page={{page_obj.previous_page_number}}"><i class="fa-solid fa-arrow-left"></i></a>
    {% endif %}

    <a href="">{{ page_obj.number }}</a>

    {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}"><i class="fa-solid fa-arrow-right"></i></a>
    {% endif %}
  </section>
  
{% endblock content %}