core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "core"

urlpatterns = [   
    path("", views.HomeView.as_view(), name="home"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("product/<int:pk>", views.s_product, name="product"),
    path("blog/", views.BlogView.as_view(), name="blog"),
    path("post/<int:pk>", views.s_blog, name="post"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact_view, name="contact"),
    path("cart/", views.CartView.as_view(), name="cart"),
]

 
# Adicione estas linhas para servir arquivos de mídia durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

setup/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('core.urls')),
    path("user/", include('userauths.urls')),
    path("ckeditor/", include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path
from . import views

app_name = "userauths"

urlpatterns = [
    path("signup/", views.register_view, name="signup"),
    path("signin/", views.login_view, name="signin"),
    path("signout/", views.logout_view, name="signout"),
]

templates/base-product.html
<div class="pro">
  <img src="/media/{{ product.image }}" alt="" onclick="window.location.href='{% url "core:product" pk=product.pk %}'">
  <div class="des">
    <span>{{ product.category }}</span>
    <h5>{{ product.title }}</h5>
    <div class="star">
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
    </div>
    <h4>R$ {{ product.price }}</h4>            
    {% if product.old_price %}
      <h4><s>R$ {{ product.old_price }}</s></h4>
    {% endif %} 
  </div>
  <button class="cartSend" data-pk="{{ product.pk }}"><i class="fa-solid fa-cart-shopping"></i></button>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}{% endblock page_title %}</title>
    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <!-- Links -->
    <!-- Css -->
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}"/>
    <!-- Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
    <!-- Scripts -->
    <!--JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- Django head -->
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
  <section id="header">
    <a href="{% url "core:home" %}"><img src="{% static 'home/img/logo.png' %}" class="logo" alt=""></a>

    <div>
      <ul id="navbar">
        {% block opc_navbar %}
          <li><a class="active" href="{% url "core:home" %}">Home</a></li>
          <li><a href="{% url "core:shop" %}">Shop</a></li>
          <li><a href="{% url "core:blog" %}">Blog</a></li>
          <li><a href="{% url "core:about" %}">About</a></li>
          <li><a href="{% url "core:contact" %}">Contact</a></li>
          <li id="lg-bag"><span>{{ request.quantidade_itens_carrinho }}</span><a href="{% url "core:cart" %}"><i class="fa-solid fa-basket-shopping"></i></a></li>
          <li id="lg-user"><a href="{% url "userauths:signin" %}"><i class="fa-solid fa-user"></i></a></li>
          <a href="#" id="close"><i class="fa-solid fa-xmark"></i></a>
        {% endblock opc_navbar %}
      </ul>
    </div>

    <div id="mobile">
      <a href="{% url "core:cart" %}"><i class="fa-solid fa-basket-shopping"></i></a>
      <i id="bar" class="fa-solid fa-bars"></i>
    </div>
  </section>

  {% block content %}{% endblock content %}

  <footer class="section-p1">
    <div class="col">
      <img class="logo" src="{% static 'home/img/logo.png' %}" alt="">
      <h4>Contact</h4>
      <p><strong>Address:</strong>address</p>
      <p><strong>Phone:</strong>(+001) 0000-0000</p>
      <p><strong>Hours:</strong>10:00 - 19:00, Mon - Sat</p>
      <div class="follow">
        <h4>Follow us</h4>
        <div class="icon">
          <i class="fa-brands fa-instagram"></i>
          <i class="fa-brands fa-twitter"></i>
          <i class="fa-brands fa-pinterest"></i>
        </div>
      </div>
    </div>

    <div class="col">
      <h4>About</h4>
      <a href="{% url "core:about" %}">About Us</a>
      <a href="#">Delivery Information</a>
      <a href="#">Privacy Policy</a>
      <a href="#">Terms & Conditions</a>
      <a href="{% url "core:contact" %}">Contact Us</a>
    </div>

    <div class="col">
      <h4>My Account</h4>
      <a href="{% url "userauths:signin" %}">Sign In</a>
      <a href="{% url "core:cart" %}">View Cart</a>
      <a href="#">My Whishlist</a>
      <a href="#">Track My Order</a>
      <a href="#">Help</a>
    </div>

    <div class="col pay">
      <h4>Payment methods</h4>
      <p>Secured Payment Gateways</p>
      <img src="{% static 'home/img/pay/pay.png' %}" alt="">
    </div>

    <div class="copyright">
      <p>© 2024, ThZt - Html CSS Ecommerce Template</p>
    </div>
    
  </footer>

  {% block extra_scripts %}{% endblock extra_scripts %}
  
  <script src="{% static 'home/js/scripts.js' %}"></script>
</body>
</html>